# Site settings
site_name: Can't Talk
title: Auto reply for everything
email:
description: The auto reply app for everything

app_url: https://play.google.com/apps/testing/com.robj.canttalk

landing_caption: Auto-Reply to Telegram, Slack, Email & more..<br>Let people know you're busy.
landing_caption_btn: Find out more

app_cta_title: Discover what all the buzz is about!
app_cta_subtext: Our app will be available to download soon! Register now to be the first to get it!

top_picks_title: Our top picks
top_picks_subtext: Our favourite places you should check out this week

features_title: What it does
features_subtext: See what Can't Talk can do for you!
features_feature_1_title: Auto-reply
features_feature_1_subtext: Automatically reply to any sms, missed calls or app messages for you.  Simple.
features_feature_2_title: Custom messages
features_feature_2_subtext: Write your own auto reply message i.e. "I'm in a meeting", "I'm driving", "Do you know what time it is?!" ..
features_feature_3_title: Specify contacts
features_feature_3_subtext: Specify which contact will get an auto reply so you only reply to who you want to.
features_feature_4_title: Reply to apps
features_feature_4_subtext: Auto reply to messages from Whatsapp, Telegram, Hangouts, Slack, Email & many others

social_banner: Follow us!

aside_title: Never be distrubed again.
aside_btn_text: Get the beta today

newsletter_title: Get in touch
newsletter_text: Leave us your best email & we'll get back to you on how we can help make your next event the best experience yet!

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "/" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: #"UA-102882403-1"
addthis_id: #ra-5644da281510c62f
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/canttalkapp
#  - title: instagram
#    url: https://instagram.com/getstuffdldn
  - title: facebook
    url: https://facebook.com/canttalkapp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
