# Site settings
site_name: Stuffd LDN
title: The ultimate guide to London's hottest food events
email:
description: A jekyll template for landing pages, portfolio and blogging

landing_caption: There has never been a better time to be a foodie in London
landing_caption_btn: Tell me more

app_cta_title: Discover what all the buzz is about!
app_cta_subtext: Our app will be available to download soon! Register now to be the first to get it!

portfolio_title: Our top picks
portfolio_subtext: Our favourite places you should check out this week
portfolio_item_1_title: STREET FEAST
portfolio_item_1_subtext: more info
portfolio_item_1_img: 1.jpg
portfolio_item_2_title: FOODIES FESTIVAL
portfolio_item_2_subtext: more info
portfolio_item_2_img: 2.jpg
portfolio_item_3_title: MEATOPIA
portfolio_item_3_subtext: more info
portfolio_item_3_img: 3.jpg
portfolio_item_4_title: VEGFESTUK LONDON
portfolio_item_4_subtext: more info
portfolio_item_4_img: 4.jpg
portfolio_item_5_title: KERB 
portfolio_item_5_subtext: more info
portfolio_item_5_img: 5.jpg
portfolio_item_6_title: URBAN FOOD FEST
portfolio_item_6_subtext: more info
portfolio_item_6_img: 6.jpg

features_title: Unlimited features, Unlimited fun
features_subtext: Check out what you can do with this app theme!
features_feature_1_title: Device Mockups
features_feature_1_subtext: Some text about this feature
features_feature_2_title: Flexible use
features_feature_2_subtext: Some text about this feature
features_feature_3_title: Free to use
features_feature_3_subtext: Some text about this feature
features_feature_4_title: Open Source
features_feature_4_subtext: Some text about this feature

social_banner: Follow us!

aside_title: Never miss another foodie event again!
aside_btn_text: Sign up for the newsletter

baseurl: "/" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "http://robj.me/foodielondon_2/" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 
data-ad-client: 
google_ad_client: 

google_analytics: #"UA-86331249-1"
addthis_id: #ra-5644da281510c62f
disqus_account: 

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/getstuffdldn
  - title: instagram
    url: https://instagram.com/getstuffdldn
  #- title: facebook
  #  url: https://facebook.com/lantoniotrento
  #- title: google-plus
  #  url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
